package com.orbis.sdb.control.theriaque;

import jakarta.jws.Oneway;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 *
 */
@WebService(name = "theriakAPIPort", targetNamespace = "http://www.ws-theriaque.localhost/server.php")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
        ObjectFactory.class
})
public interface TheriakAPIPort {

    /**
     * generateWSDl
     *
     */
    @WebMethod(action = "http://www.ws-theriaque.localhost/server.php#generateWSDl")
    @Oneway
    void generateWSDl();

    /**
     * Renvoie des alertes apr賠une analyse d'ordonnance
     *
     * @param listPrescription
     * @param listSchemaPosologie
     * @param natureAlerteCipemg
     * @param niveauGraviteInteraction
     * @param patient
     * @param typeAlerteSortie
     * @return
     *     returns com.orbis.sdb.control.theriaque.AlertesOrdonnance
     */
    @WebMethod(operationName = "get_analyse_ordonnance", action = "http://www.ws-theriaque.localhost/server.php#get_analyse_ordonnance")
    @WebResult(partName = "return")
    AlertesOrdonnance getAnalyseOrdonnance(
            @WebParam(name = "patient", partName = "patient")
            ObjPatient patient,
            @WebParam(name = "list_prescription", partName = "list_prescription")
            ArrayOfObjPrescription listPrescription,
            @WebParam(name = "list_schema_posologie", partName = "list_schema_posologie")
            ArrayOfObjSchemaPosologie listSchemaPosologie,
            @WebParam(name = "type_alerte_sortie", partName = "type_alerte_sortie")
            String typeAlerteSortie,
            @WebParam(name = "nature_alerte_cipemg", partName = "nature_alerte_cipemg")
            String natureAlerteCipemg,
            @WebParam(name = "niveau_gravite_interaction", partName = "niveau_gravite_interaction")
            String niveauGraviteInteraction);

    /**
     * Enter description here ...
     *
     * @param libProd
     * @param monoVir
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheSpeTxt
     */
    @WebMethod(operationName = "get_the_spe_txt", action = "http://www.ws-theriaque.localhost/server.php#get_the_spe_txt")
    @WebResult(partName = "return")
    ArrayOfRowGetTheSpeTxt getTheSpeTxt(
            @WebParam(name = "lib_prod", partName = "lib_prod")
            String libProd,
            @WebParam(name = "mono_vir", partName = "mono_vir")
            String monoVir);

    /**
     * Enter description here ...
     *
     * @param codeId
     * @param monoVir
     * @param varType
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheSpecialite
     */
    @WebMethod(operationName = "get_the_specialite", action = "http://www.ws-theriaque.localhost/server.php#get_the_specialite")
    @WebResult(partName = "return")
    ArrayOfRowGetTheSpecialite getTheSpecialite(
            @WebParam(name = "code_id", partName = "code_id")
            String codeId,
            @WebParam(name = "var_type", partName = "var_type")
            String varType,
            @WebParam(name = "mono_vir", partName = "mono_vir")
            String monoVir);

    /**
     * Enter description here ...
     *
     * @param codeId
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheVoieSpe
     */
    @WebMethod(operationName = "get_the_voie_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_voie_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheVoieSpe getTheVoieSpe(
            @WebParam(name = "code_id", partName = "code_id")
            String codeId);

    /**
     * Enter description here ...
     *
     * @param codeId
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheFormeTxtSpe
     */
    @WebMethod(operationName = "get_the_forme_txt_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_forme_txt_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheFormeTxtSpe getTheFormeTxtSpe(
            @WebParam(name = "code_id", partName = "code_id")
            String codeId);

    /**
     * Enter description here ...
     *
     * @param codeId
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheRefForme
     */
    @WebMethod(operationName = "get_the_ref_forme", action = "http://www.ws-theriaque.localhost/server.php#get_the_ref_forme")
    @WebResult(partName = "return")
    ArrayOfRowGetTheRefForme getTheRefForme(
            @WebParam(name = "code_id", partName = "code_id")
            String codeId);

    /**
     * Enter description here ...
     *
     * @param libPrdt
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetThePdtSpe
     */
    @WebMethod(operationName = "get_the_pdt_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_pdt_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetThePdtSpe getThePdtSpe(
            @WebParam(name = "lib_prdt", partName = "lib_prdt")
            String libPrdt);

    /**
     * Enter description here ...
     *
     * @param codeSpe
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheFormeSpe
     */
    @WebMethod(operationName = "get_the_forme_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_forme_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheFormeSpe getTheFormeSpe(
            @WebParam(name = "code_spe", partName = "code_spe")
            String codeSpe);

    /**
     * Enter description here ...
     *
     * @param codeSpe
     * @param typeId
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheFormeCompSpe
     */
    @WebMethod(operationName = "get_the_forme_comp_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_forme_comp_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheFormeCompSpe getTheFormeCompSpe(
            @WebParam(name = "code_spe", partName = "code_spe")
            String codeSpe,
            @WebParam(name = "type_id", partName = "type_id")
            String typeId);

    /**
     * Enter description here ...
     *
     * @param codeId
     * @param typeId
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetThePresentation
     */
    @WebMethod(operationName = "get_the_presentation", action = "http://www.ws-theriaque.localhost/server.php#get_the_presentation")
    @WebResult(partName = "return")
    ArrayOfRowGetThePresentation getThePresentation(
            @WebParam(name = "code_id", partName = "code_id")
            String codeId,
            @WebParam(name = "type_id", partName = "type_id")
            String typeId);

    /**
     * Enter description here ...
     *
     * @param cip
     * @param vartype
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetThePreCdt
     */
    @WebMethod(operationName = "get_the_pre_cdt", action = "http://www.ws-theriaque.localhost/server.php#get_the_pre_cdt")
    @WebResult(partName = "return")
    ArrayOfRowGetThePreCdt getThePreCdt(
            @WebParam(name = "cip", partName = "cip")
            String cip,
            @WebParam(name = "vartype", partName = "vartype")
            String vartype);

    /**
     * Enter description here ...
     *
     * @param cip
     * @param vartype
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetThePreStatut
     */
    @WebMethod(operationName = "get_the_pre_statut", action = "http://www.ws-theriaque.localhost/server.php#get_the_pre_statut")
    @WebResult(partName = "return")
    ArrayOfRowGetThePreStatut getThePreStatut(
            @WebParam(name = "cip", partName = "cip")
            String cip,
            @WebParam(name = "vartype", partName = "vartype")
            String vartype);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @param typeid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetThePrePri
     */
    @WebMethod(operationName = "get_the_pre_pri", action = "http://www.ws-theriaque.localhost/server.php#get_the_pre_pri")
    @WebResult(partName = "return")
    ArrayOfRowGetThePrePri getThePrePri(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid,
            @WebParam(name = "typeid", partName = "typeid")
            String typeid);

    /**
     * Enter description here ...
     *
     * @param idspe
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheSpeStatut
     */
    @WebMethod(operationName = "get_the_spe_statut", action = "http://www.ws-theriaque.localhost/server.php#get_the_spe_statut")
    @WebResult(partName = "return")
    ArrayOfRowGetTheSpeStatut getTheSpeStatut(
            @WebParam(name = "idspe", partName = "idspe")
            String idspe);

    /**
     * Enter description here ...
     *
     * @param cip
     * @param vartype
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetThePreDsp
     */
    @WebMethod(operationName = "get_the_pre_dsp", action = "http://www.ws-theriaque.localhost/server.php#get_the_pre_dsp")
    @WebResult(partName = "return")
    ArrayOfRowGetThePreDsp getThePreDsp(
            @WebParam(name = "cip", partName = "cip")
            String cip,
            @WebParam(name = "vartype", partName = "vartype")
            String vartype);

    /**
     * Enter description here ...
     *
     * @param cip
     * @param vartype
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetThePreCsv
     */
    @WebMethod(operationName = "get_the_pre_csv", action = "http://www.ws-theriaque.localhost/server.php#get_the_pre_csv")
    @WebResult(partName = "return")
    ArrayOfRowGetThePreCsv getThePreCsv(
            @WebParam(name = "cip", partName = "cip")
            String cip,
            @WebParam(name = "vartype", partName = "vartype")
            String vartype);

    /**
     * Enter description here ...
     *
     * @param cip
     * @param vartype
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetThePreRbt
     */
    @WebMethod(operationName = "get_the_pre_rbt", action = "http://www.ws-theriaque.localhost/server.php#get_the_pre_rbt")
    @WebResult(partName = "return")
    ArrayOfRowGetThePreRbt getThePreRbt(
            @WebParam(name = "cip", partName = "cip")
            String cip,
            @WebParam(name = "vartype", partName = "vartype")
            String vartype);

    /**
     *
     * @param gravite
     * @param listesp
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheGtiamId
     */
    @WebMethod(operationName = "get_the_gtiam_id", action = "http://www.ws-theriaque.localhost/server.php#get_the_gtiam_id")
    @WebResult(partName = "return")
    ArrayOfRowGetTheGtiamId getTheGtiamId(
            @WebParam(name = "listesp", partName = "listesp")
            String listesp,
            @WebParam(name = "gravite", partName = "gravite")
            String gravite);

    /**
     * Enter description here ...
     *
     * @param listFic
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheGtiamTxt
     */
    @WebMethod(operationName = "get_the_gtiam_txt", action = "http://www.ws-theriaque.localhost/server.php#get_the_gtiam_txt")
    @WebResult(partName = "return")
    ArrayOfRowGetTheGtiamTxt getTheGtiamTxt(
            @WebParam(name = "list_fic", partName = "list_fic")
            String listFic);

    /**
     * Enter description here ...
     *
     * @param listFic
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheGtiamDet
     */
    @WebMethod(operationName = "get_the_gtiam_det", action = "http://www.ws-theriaque.localhost/server.php#get_the_gtiam_det")
    @WebResult(partName = "return")
    ArrayOfRowGetTheGtiamDet getTheGtiamDet(
            @WebParam(name = "list_fic", partName = "list_fic")
            String listFic);

    /**
     * Enter description here ...
     *
     * @param codeId
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheInterSpe
     */
    @WebMethod(operationName = "get_the_inter_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_inter_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheInterSpe getTheInterSpe(
            @WebParam(name = "code_id", partName = "code_id")
            String codeId);

    /**
     * Enter description here ...
     *
     * @param argu
     * @param ccCs
     * @param typ
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheCdfToCim10
     */
    @WebMethod(operationName = "get_the_cdf_to_cim10", action = "http://www.ws-theriaque.localhost/server.php#get_the_cdf_to_cim10")
    @WebResult(partName = "return")
    ArrayOfRowGetTheCdfToCim10 getTheCdfToCim10(
            @WebParam(name = "cc_cs", partName = "cc_cs")
            String ccCs,
            @WebParam(name = "argu", partName = "argu")
            String argu,
            @WebParam(name = "typ", partName = "typ")
            String typ);

    /**
     * Enter description here ...
     *
     * @param argu
     * @param ccCs
     * @param typ
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheCim10ToCdf
     */
    @WebMethod(operationName = "get_the_cim10_to_cdf", action = "http://www.ws-theriaque.localhost/server.php#get_the_cim10_to_cdf")
    @WebResult(partName = "return")
    ArrayOfRowGetTheCim10ToCdf getTheCim10ToCdf(
            @WebParam(name = "cc_cs", partName = "cc_cs")
            String ccCs,
            @WebParam(name = "argu", partName = "argu")
            String argu,
            @WebParam(name = "typ", partName = "typ")
            String typ);

    /**
     * Enter description here ...
     *
     * @param codeId
     * @param typId
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheEffindSpe
     */
    @WebMethod(operationName = "get_the_effind_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_effind_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheEffindSpe getTheEffindSpe(
            @WebParam(name = "code_id", partName = "code_id")
            String codeId,
            @WebParam(name = "typ_id", partName = "typ_id")
            String typId);

    /**
     * Enter description here ...
     *
     * @param codeId
     * @param typId
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheDetEffind
     */
    @WebMethod(operationName = "get_the_det_effind", action = "http://www.ws-theriaque.localhost/server.php#get_the_det_effind")
    @WebResult(partName = "return")
    ArrayOfRowGetTheDetEffind getTheDetEffind(
            @WebParam(name = "code_id", partName = "code_id")
            String codeId,
            @WebParam(name = "typ_id", partName = "typ_id")
            String typId);

    /**
     * Enter description here ...
     *
     * @param lstFic
     * @param typ
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheDetEffindSd
     */
    @WebMethod(operationName = "get_the_det_effind_sd", action = "http://www.ws-theriaque.localhost/server.php#get_the_det_effind_sd")
    @WebResult(partName = "return")
    ArrayOfRowGetTheDetEffindSd getTheDetEffindSd(
            @WebParam(name = "lst_fic", partName = "lst_fic")
            String lstFic,
            @WebParam(name = "typ", partName = "typ")
            String typ);

    /**
     * Enter description here ...
     *
     * @param codeind
     * @param codespe
     * @param typ
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheRefEffind
     */
    @WebMethod(operationName = "get_the_ref_effind", action = "http://www.ws-theriaque.localhost/server.php#get_the_ref_effind")
    @WebResult(partName = "return")
    ArrayOfRowGetTheRefEffind getTheRefEffind(
            @WebParam(name = "codeind", partName = "codeind")
            String codeind,
            @WebParam(name = "codespe", partName = "codespe")
            String codespe,
            @WebParam(name = "typ", partName = "typ")
            String typ);

    /**
     * Enter description here ...
     *
     * @param codeind
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheEffindId
     */
    @WebMethod(operationName = "get_the_effind_id", action = "http://www.ws-theriaque.localhost/server.php#get_the_effind_id")
    @WebResult(partName = "return")
    ArrayOfRowGetTheEffindId getTheEffindId(
            @WebParam(name = "codeind", partName = "codeind")
            String codeind);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @param typid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheCipemgSpe
     */
    @WebMethod(operationName = "get_the_cipemg_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_cipemg_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheCipemgSpe getTheCipemgSpe(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid,
            @WebParam(name = "typid", partName = "typid")
            String typid);

    /**
     * Enter description here ...
     *
     * @param codeter
     * @param idcipemg
     * @param idseq
     * @param nature
     * @param typid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheDetCipemg
     */
    @WebMethod(operationName = "get_the_det_cipemg", action = "http://www.ws-theriaque.localhost/server.php#get_the_det_cipemg")
    @WebResult(partName = "return")
    ArrayOfRowGetTheDetCipemg getTheDetCipemg(
            @WebParam(name = "idcipemg", partName = "idcipemg")
            String idcipemg,
            @WebParam(name = "codeter", partName = "codeter")
            String codeter,
            @WebParam(name = "nature", partName = "nature")
            String nature,
            @WebParam(name = "idseq", partName = "idseq")
            String idseq,
            @WebParam(name = "typid", partName = "typid")
            String typid);

    /**
     * Enter description here ...
     *
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheNivGrav
     */
    @WebMethod(operationName = "get_the_niv_grav", action = "http://www.ws-theriaque.localhost/server.php#get_the_niv_grav")
    @WebResult(partName = "return")
    ArrayOfRowGetTheNivGrav getTheNivGrav();

    /**
     * Enter description here ...
     *
     * @param libtxt
     * @param typci
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheCipemg
     */
    @WebMethod(operationName = "get_the_cipemg", action = "http://www.ws-theriaque.localhost/server.php#get_the_cipemg")
    @WebResult(partName = "return")
    ArrayOfRowGetTheCipemg getTheCipemg(
            @WebParam(name = "libtxt", partName = "libtxt")
            String libtxt,
            @WebParam(name = "typci", partName = "typci")
            String typci);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @param idcipemg
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheRefCipemg
     */
    @WebMethod(operationName = "get_the_ref_cipemg", action = "http://www.ws-theriaque.localhost/server.php#get_the_ref_cipemg")
    @WebResult(partName = "return")
    ArrayOfRowGetTheRefCipemg getTheRefCipemg(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid,
            @WebParam(name = "idcipemg", partName = "idcipemg")
            String idcipemg);

    /**
     * Enter description here ...
     *
     * @param dtRef
     * @param idspe
     * @param nofic
     * @param typ
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheRefCipemgRcp
     */
    @WebMethod(operationName = "get_the_ref_cipemg_rcp", action = "http://www.ws-theriaque.localhost/server.php#get_the_ref_cipemg_rcp")
    @WebResult(partName = "return")
    ArrayOfRowGetTheRefCipemgRcp getTheRefCipemgRcp(
            @WebParam(name = "idspe", partName = "idspe")
            String idspe,
            @WebParam(name = "dt_ref", partName = "dt_ref")
            String dtRef,
            @WebParam(name = "nofic", partName = "nofic")
            String nofic,
            @WebParam(name = "typ", partName = "typ")
            String typ);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @param lstter
     * @param typid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheCipemgSpeTer
     */
    @WebMethod(operationName = "get_the_cipemg_spe_ter", action = "http://www.ws-theriaque.localhost/server.php#get_the_cipemg_spe_ter")
    @WebResult(partName = "return")
    ArrayOfRowGetTheCipemgSpeTer getTheCipemgSpeTer(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid,
            @WebParam(name = "typid", partName = "typid")
            String typid,
            @WebParam(name = "lstter", partName = "lstter")
            String lstter);

    /**
     * Enter description here ...
     *
     * @param code
     * @param typ
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetThePoso
     */
    @WebMethod(operationName = "get_the_poso", action = "http://www.ws-theriaque.localhost/server.php#get_the_poso")
    @WebResult(partName = "return")
    ArrayOfRowGetThePoso getThePoso(
            @WebParam(name = "code", partName = "code")
            String code,
            @WebParam(name = "typ", partName = "typ")
            String typ);

    /**
     * Enter description here ...
     *
     * @param code
     * @param typ
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheSchemaPoso
     */
    @WebMethod(operationName = "get_the_schema_poso", action = "http://www.ws-theriaque.localhost/server.php#get_the_schema_poso")
    @WebResult(partName = "return")
    ArrayOfRowGetTheSchemaPoso getTheSchemaPoso(
            @WebParam(name = "code", partName = "code")
            String code,
            @WebParam(name = "typ", partName = "typ")
            String typ);

    /**
     * Enter description here ...
     *
     * @param code
     * @param typ
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheDetPoso
     */
    @WebMethod(operationName = "get_the_det_poso", action = "http://www.ws-theriaque.localhost/server.php#get_the_det_poso")
    @WebResult(partName = "return")
    ArrayOfRowGetTheDetPoso getTheDetPoso(
            @WebParam(name = "code", partName = "code")
            String code,
            @WebParam(name = "typ", partName = "typ")
            String typ);

    /**
     * Enter description here ...
     *
     * @param lstidpos
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetThePosoText
     */
    @WebMethod(operationName = "get_the_poso_text", action = "http://www.ws-theriaque.localhost/server.php#get_the_poso_text")
    @WebResult(partName = "return")
    ArrayOfRowGetThePosoText getThePosoText(
            @WebParam(name = "lstidpos", partName = "lstidpos")
            String lstidpos);

    /**
     * Enter description here ...
     *
     * @param idspe
     * @param typ
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetThePosoComUti
     */
    @WebMethod(operationName = "get_the_poso_com_uti", action = "http://www.ws-theriaque.localhost/server.php#get_the_poso_com_uti")
    @WebResult(partName = "return")
    ArrayOfRowGetThePosoComUti getThePosoComUti(
            @WebParam(name = "idspe", partName = "idspe")
            String idspe,
            @WebParam(name = "typ", partName = "typ")
            String typ);

    /**
     * Enter description here ...
     *
     * @param code
     * @param typ
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheDetPosoSpe
     */
    @WebMethod(operationName = "get_the_det_poso_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_det_poso_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheDetPosoSpe getTheDetPosoSpe(
            @WebParam(name = "code", partName = "code")
            String code,
            @WebParam(name = "typ", partName = "typ")
            String typ);

    /**
     * Enter description here ...
     *
     * @param arg
     * @param typ
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetThePrfPat
     */
    @WebMethod(operationName = "get_the_prf_pat", action = "http://www.ws-theriaque.localhost/server.php#get_the_prf_pat")
    @WebResult(partName = "return")
    ArrayOfRowGetThePrfPat getThePrfPat(
            @WebParam(name = "typ", partName = "typ")
            String typ,
            @WebParam(name = "arg", partName = "arg")
            String arg);

    /**
     * Enter description here ...
     *
     * @param aG
     * @param idSpe
     * @param patho
     * @param poi
     * @param sexe
     * @param tA
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetThePrfPoso
     */
    @WebMethod(operationName = "get_the_prf_poso", action = "http://www.ws-theriaque.localhost/server.php#get_the_prf_poso")
    @WebResult(partName = "return")
    ArrayOfRowGetThePrfPoso getThePrfPoso(
            @WebParam(name = "id_spe", partName = "id_spe")
            String idSpe,
            @WebParam(name = "a_g", partName = "a_g")
            String aG,
            @WebParam(name = "poi", partName = "poi")
            String poi,
            @WebParam(name = "patho", partName = "patho")
            String patho,
            @WebParam(name = "t_a", partName = "t_a")
            String tA,
            @WebParam(name = "sexe", partName = "sexe")
            String sexe);

    /**
     * Enter description here ...
     *
     * @param lstHyper
     * @param lstSpe
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetThePrfHyper
     */
    @WebMethod(operationName = "get_the_prf_hyper", action = "http://www.ws-theriaque.localhost/server.php#get_the_prf_hyper")
    @WebResult(partName = "return")
    ArrayOfRowGetThePrfHyper getThePrfHyper(
            @WebParam(name = "lst_spe", partName = "lst_spe")
            String lstSpe,
            @WebParam(name = "lst_hyper", partName = "lst_hyper")
            String lstHyper);

    /**
     * Enter description here ...
     *
     * @param listCip
     * @param profilPatient
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetAlerteOrdonnance
     */
    @WebMethod(operationName = "get_alerte_ordonnance", action = "http://www.ws-theriaque.localhost/server.php#get_alerte_ordonnance")
    @WebResult(partName = "return")
    ArrayOfRowGetAlerteOrdonnance getAlerteOrdonnance(
            @WebParam(name = "profil_patient", partName = "profil_patient")
            String profilPatient,
            @WebParam(name = "list_cip", partName = "list_cip")
            String listCip);

    /**
     * Enter description here ...
     *
     * @param patho
     * @param tAge
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetThePrfFils
     */
    @WebMethod(operationName = "get_the_prf_fils", action = "http://www.ws-theriaque.localhost/server.php#get_the_prf_fils")
    @WebResult(partName = "return")
    ArrayOfRowGetThePrfFils getThePrfFils(
            @WebParam(name = "t_age", partName = "t_age")
            String tAge,
            @WebParam(name = "patho", partName = "patho")
            String patho);

    /**
     * Enter description here ...
     *
     * @param cdfNc
     * @param cdfNn
     * @param idSpe
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetThePrfIndic
     */
    @WebMethod(operationName = "get_the_prf_indic", action = "http://www.ws-theriaque.localhost/server.php#get_the_prf_indic")
    @WebResult(partName = "return")
    ArrayOfRowGetThePrfIndic getThePrfIndic(
            @WebParam(name = "cdf_nc", partName = "cdf_nc")
            String cdfNc,
            @WebParam(name = "cdf_nn", partName = "cdf_nn")
            String cdfNn,
            @WebParam(name = "id_spe", partName = "id_spe")
            String idSpe);

    /**
     * Enter description here ...
     *
     * @param mode
     * @param var
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheIndicPrincipale
     */
    @WebMethod(operationName = "get_the_indic_principale", action = "http://www.ws-theriaque.localhost/server.php#get_the_indic_principale")
    @WebResult(partName = "return")
    ArrayOfRowGetTheIndicPrincipale getTheIndicPrincipale(
            @WebParam(name = "var", partName = "var")
            String var,
            @WebParam(name = "mode", partName = "mode")
            String mode);

    /**
     * Enter description here ...
     *
     * @param mode
     * @param var
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheNatureIndicByPrincipale
     */
    @WebMethod(operationName = "get_the_nature_indic_by_principale", action = "http://www.ws-theriaque.localhost/server.php#get_the_nature_indic_by_principale")
    @WebResult(partName = "return")
    ArrayOfRowGetTheNatureIndicByPrincipale getTheNatureIndicByPrincipale(
            @WebParam(name = "var", partName = "var")
            String var,
            @WebParam(name = "mode", partName = "mode")
            String mode);

    /**
     * Enter description here ...
     *
     * @param code
     * @param mode
     * @param type
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheSpeByIndication
     */
    @WebMethod(operationName = "get_the_spe_by_indication", action = "http://www.ws-theriaque.localhost/server.php#get_the_spe_by_indication")
    @WebResult(partName = "return")
    ArrayOfRowGetTheSpeByIndication getTheSpeByIndication(
            @WebParam(name = "code", partName = "code")
            String code,
            @WebParam(name = "type", partName = "type")
            String type,
            @WebParam(name = "mode", partName = "mode")
            String mode);

    /**
     * Enter description here ...
     *
     * @param code
     * @return
     *     returns com.orbis.sdb.control.theriaque.RowGetTheFicheIndicationByCode
     */
    @WebMethod(operationName = "get_the_fiche_indication_by_code", action = "http://www.ws-theriaque.localhost/server.php#get_the_fiche_indication_by_code")
    @WebResult(partName = "return")
    RowGetTheFicheIndicationByCode getTheFicheIndicationByCode(
            @WebParam(name = "code", partName = "code")
            String code);

    /**
     * Enter description here ...
     *
     * @param code
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetCodeFicheIndicationBySpe
     */
    @WebMethod(operationName = "get_code_fiche_indication_by_spe", action = "http://www.ws-theriaque.localhost/server.php#get_code_fiche_indication_by_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetCodeFicheIndicationBySpe getCodeFicheIndicationBySpe(
            @WebParam(name = "code", partName = "code")
            String code);

    /**
     * Enter description here ...
     *
     * @param code
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetDetailFichesBySpe
     */
    @WebMethod(operationName = "get_detail_fiches_by_spe", action = "http://www.ws-theriaque.localhost/server.php#get_detail_fiches_by_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetDetailFichesBySpe getDetailFichesBySpe(
            @WebParam(name = "code", partName = "code")
            String code);

    /**
     * Enter description here ...
     *
     * @param code
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheFicheIndicationByNatureIndication
     */
    @WebMethod(operationName = "get_the_fiche_indication_by_nature_indication", action = "http://www.ws-theriaque.localhost/server.php#get_the_fiche_indication_by_nature_indication")
    @WebResult(partName = "return")
    ArrayOfRowGetTheFicheIndicationByNatureIndication getTheFicheIndicationByNatureIndication(
            @WebParam(name = "code", partName = "code")
            String code);

    /**
     * Enter description here ...
     *
     * @param code
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetDetailFicheIndicationByTypeIndication
     */
    @WebMethod(operationName = "get_detail_fiche_indication_by_type_indication", action = "http://www.ws-theriaque.localhost/server.php#get_detail_fiche_indication_by_type_indication")
    @WebResult(partName = "return")
    ArrayOfRowGetDetailFicheIndicationByTypeIndication getDetailFicheIndicationByTypeIndication(
            @WebParam(name = "code", partName = "code")
            String code);

    /**
     * Enter description here ...
     *
     * @param codeind
     * @param codespe
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheRefInd
     */
    @WebMethod(operationName = "get_the_ref_ind", action = "http://www.ws-theriaque.localhost/server.php#get_the_ref_ind")
    @WebResult(partName = "return")
    ArrayOfRowGetTheRefInd getTheRefInd(
            @WebParam(name = "codeind", partName = "codeind")
            String codeind,
            @WebParam(name = "codespe", partName = "codespe")
            String codespe);

    /**
     * Enter description here ...
     *
     * @param codeind
     * @param codespe
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheSmrSpe
     */
    @WebMethod(operationName = "get_the_smr_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_smr_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheSmrSpe getTheSmrSpe(
            @WebParam(name = "codeind", partName = "codeind")
            String codeind,
            @WebParam(name = "codespe", partName = "codespe")
            String codespe);

    /**
     * Enter description here ...
     *
     * @param codefic
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheAtrSpe
     */
    @WebMethod(operationName = "get_the_atr_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_atr_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheAtrSpe getTheAtrSpe(
            @WebParam(name = "codefic", partName = "codefic")
            String codefic);

    /**
     * Enter description here ...
     *
     * @param codeForme
     * @return
     *     returns com.orbis.sdb.control.theriaque.RowGetTheFormeParCodeForme
     */
    @WebMethod(operationName = "get_the_forme_par_code_forme", action = "http://www.ws-theriaque.localhost/server.php#get_the_forme_par_code_forme")
    @WebResult(partName = "return")
    RowGetTheFormeParCodeForme getTheFormeParCodeForme(
            @WebParam(name = "code_forme", partName = "code_forme")
            String codeForme);

    /**
     * Enter description here ...
     *
     * @param libelleForme
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheFormeParLibelle
     */
    @WebMethod(operationName = "get_the_forme_par_libelle", action = "http://www.ws-theriaque.localhost/server.php#get_the_forme_par_libelle")
    @WebResult(partName = "return")
    ArrayOfRowGetTheFormeParLibelle getTheFormeParLibelle(
            @WebParam(name = "libelle_forme", partName = "libelle_forme")
            String libelleForme);

    /**
     * Enter description here ...
     *
     * @param codeForme
     * @param libSpe
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetSpeByCodeForme
     */
    @WebMethod(operationName = "get_spe_by_code_forme", action = "http://www.ws-theriaque.localhost/server.php#get_spe_by_code_forme")
    @WebResult(partName = "return")
    ArrayOfRowGetSpeByCodeForme getSpeByCodeForme(
            @WebParam(name = "code_forme", partName = "code_forme")
            String codeForme,
            @WebParam(name = "lib_spe", partName = "lib_spe")
            String libSpe);

    /**
     * Enter description here ...
     *
     * @param codeav
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheAtrCompl
     */
    @WebMethod(operationName = "get_the_atr_compl", action = "http://www.ws-theriaque.localhost/server.php#get_the_atr_compl")
    @WebResult(partName = "return")
    ArrayOfRowGetTheAtrCompl getTheAtrCompl(
            @WebParam(name = "codeav", partName = "codeav")
            String codeav);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @param typid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheChoix
     */
    @WebMethod(operationName = "get_the_choix", action = "http://www.ws-theriaque.localhost/server.php#get_the_choix")
    @WebResult(partName = "return")
    ArrayOfRowGetTheChoix getTheChoix(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid,
            @WebParam(name = "typid", partName = "typid")
            String typid);

    /**
     * Enter description here ...
     *
     * @param codefic
     * @param vartyp
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheDocSpe
     */
    @WebMethod(operationName = "get_the_doc_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_doc_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheDocSpe getTheDocSpe(
            @WebParam(name = "codefic", partName = "codefic")
            String codefic,
            @WebParam(name = "vartyp", partName = "vartyp")
            String vartyp);

    /**
     * Enter description here ...
     *
     * @param presDc
     * @param txt
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheGenVirTxt
     */
    @WebMethod(operationName = "get_the_gen_vir_txt", action = "http://www.ws-theriaque.localhost/server.php#get_the_gen_vir_txt")
    @WebResult(partName = "return")
    ArrayOfRowGetTheGenVirTxt getTheGenVirTxt(
            @WebParam(name = "txt", partName = "txt")
            String txt,
            @WebParam(name = "pres_dc", partName = "pres_dc")
            String presDc);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @param vartyp
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheGenSpe
     */
    @WebMethod(operationName = "get_the_gen_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_gen_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheGenSpe getTheGenSpe(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid,
            @WebParam(name = "vartyp", partName = "vartyp")
            String vartyp);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @return
     *     returns com.orbis.sdb.control.theriaque.RowGetTheVirId
     */
    @WebMethod(operationName = "get_the_vir_id", action = "http://www.ws-theriaque.localhost/server.php#get_the_vir_id")
    @WebResult(partName = "return")
    RowGetTheVirId getTheVirId(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid);

    /**
     * Enter description here ...
     *
     * @param code
     * @return
     *     returns com.orbis.sdb.control.theriaque.RowGetTheVoieParCode
     */
    @WebMethod(operationName = "get_the_voie_par_code", action = "http://www.ws-theriaque.localhost/server.php#get_the_voie_par_code")
    @WebResult(partName = "return")
    RowGetTheVoieParCode getTheVoieParCode(
            @WebParam(name = "code", partName = "code")
            String code);

    /**
     * Enter description here ...
     *
     * @param libelle
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheVoieParLibelle
     */
    @WebMethod(operationName = "get_the_voie_par_libelle", action = "http://www.ws-theriaque.localhost/server.php#get_the_voie_par_libelle")
    @WebResult(partName = "return")
    ArrayOfRowGetTheVoieParLibelle getTheVoieParLibelle(
            @WebParam(name = "libelle", partName = "libelle")
            String libelle);

    /**
     * Enter description here ...
     *
     * @param codeVoie
     * @param libSpe
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheSpeParVoie
     */
    @WebMethod(operationName = "get_the_spe_par_voie", action = "http://www.ws-theriaque.localhost/server.php#get_the_spe_par_voie")
    @WebResult(partName = "return")
    ArrayOfRowGetTheSpeParVoie getTheSpeParVoie(
            @WebParam(name = "code_voie", partName = "code_voie")
            String codeVoie,
            @WebParam(name = "lib_spe", partName = "lib_spe")
            String libSpe);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheEphmra
     */
    @WebMethod(operationName = "get_the_ephmra", action = "http://www.ws-theriaque.localhost/server.php#get_the_ephmra")
    @WebResult(partName = "return")
    ArrayOfRowGetTheEphmra getTheEphmra(
            @WebParam(name = "codeid", partName = "codeid")
            int codeid);

    /**
     * Enter description here ...
     *
     * @param type
     * @param var
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheCph
     */
    @WebMethod(operationName = "get_the_cph", action = "http://www.ws-theriaque.localhost/server.php#get_the_cph")
    @WebResult(partName = "return")
    ArrayOfRowGetTheCph getTheCph(
            @WebParam(name = "var", partName = "var")
            String var,
            @WebParam(name = "type", partName = "type")
            String type);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheAtc
     */
    @WebMethod(operationName = "get_the_atc", action = "http://www.ws-theriaque.localhost/server.php#get_the_atc")
    @WebResult(partName = "return")
    ArrayOfRowGetTheAtc getTheAtc(
            @WebParam(name = "codeid", partName = "codeid")
            int codeid);

    /**
     * Enter description here ...
     *
     * @param codeId
     * @param typeId
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheAtcDdd
     */
    @WebMethod(operationName = "get_the_atc_ddd", action = "http://www.ws-theriaque.localhost/server.php#get_the_atc_ddd")
    @WebResult(partName = "return")
    ArrayOfRowGetTheAtcDdd getTheAtcDdd(
            @WebParam(name = "code_id", partName = "code_id")
            String codeId,
            @WebParam(name = "type_id", partName = "type_id")
            String typeId);

    /**
     * Enter description here ...
     *
     * @param libTxt
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheAphpTxt
     */
    @WebMethod(operationName = "get_the_aphp_txt", action = "http://www.ws-theriaque.localhost/server.php#get_the_aphp_txt")
    @WebResult(partName = "return")
    ArrayOfRowGetTheAphpTxt getTheAphpTxt(
            @WebParam(name = "lib_txt", partName = "lib_txt")
            String libTxt);

    /**
     * Enter description here ...
     *
     * @param codeId
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheAphpId
     */
    @WebMethod(operationName = "get_the_aphp_id", action = "http://www.ws-theriaque.localhost/server.php#get_the_aphp_id")
    @WebResult(partName = "return")
    ArrayOfRowGetTheAphpId getTheAphpId(
            @WebParam(name = "code_id", partName = "code_id")
            String codeId);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheCim10Terrain
     */
    @WebMethod(operationName = "get_the_cim10", action = "http://www.ws-theriaque.localhost/server.php#get_the_cim10")
    @WebResult(partName = "return")
    ArrayOfRowGetTheCim10Terrain getTheCim10(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid);

    /**
     * Enter description here ...
     *
     * @param type
     * @param var
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheCim10
     */
    @WebMethod(operationName = "get_the_cim_10", action = "http://www.ws-theriaque.localhost/server.php#get_the_cim_10")
    @WebResult(partName = "return")
    ArrayOfRowGetTheCim10 getTheCim10(
            @WebParam(name = "type", partName = "type")
            String type,
            @WebParam(name = "var", partName = "var")
            String var);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheAtcId
     */
    @WebMethod(operationName = "get_the_atc_id", action = "http://www.ws-theriaque.localhost/server.php#get_the_atc_id")
    @WebResult(partName = "return")
    ArrayOfRowGetTheAtcId getTheAtcId(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid);

    /**
     *
     * @param codeLg
     * @param libTxt
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheAtcTxt
     */
    @WebMethod(operationName = "get_the_atc_txt", action = "http://www.ws-theriaque.localhost/server.php#get_the_atc_txt")
    @WebResult(partName = "return")
    ArrayOfRowGetTheAtcTxt getTheAtcTxt(
            @WebParam(name = "lib_txt", partName = "lib_txt")
            String libTxt,
            @WebParam(name = "code_lg", partName = "code_lg")
            String codeLg);

    /**
     *
     * @param codeId
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheAtcAtc
     */
    @WebMethod(operationName = "get_the_atc_atc", action = "http://www.ws-theriaque.localhost/server.php#get_the_atc_atc")
    @WebResult(partName = "return")
    ArrayOfRowGetTheAtcAtc getTheAtcAtc(
            @WebParam(name = "code_id", partName = "code_id")
            String codeId);

    /**
     *
     * @param codeId
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheAtcSpe
     */
    @WebMethod(operationName = "get_the_atc_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_atc_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheAtcSpe getTheAtcSpe(
            @WebParam(name = "code_id", partName = "code_id")
            String codeId);

    /**
     *
     * @param codeLg
     * @param libTxt
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheEphmraTxt
     */
    @WebMethod(operationName = "get_the_ephmra_txt", action = "http://www.ws-theriaque.localhost/server.php#get_the_ephmra_txt")
    @WebResult(partName = "return")
    ArrayOfRowGetTheEphmraTxt getTheEphmraTxt(
            @WebParam(name = "lib_txt", partName = "lib_txt")
            String libTxt,
            @WebParam(name = "code_lg", partName = "code_lg")
            String codeLg);

    /**
     *
     * @param codeId
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheEphmraId
     */
    @WebMethod(operationName = "get_the_ephmra_id", action = "http://www.ws-theriaque.localhost/server.php#get_the_ephmra_id")
    @WebResult(partName = "return")
    ArrayOfRowGetTheEphmraId getTheEphmraId(
            @WebParam(name = "code_id", partName = "code_id")
            String codeId);

    /**
     *
     * @param codeId
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheEphmraSpe
     */
    @WebMethod(operationName = "get_the_ephmra_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_ephmra_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheEphmraSpe getTheEphmraSpe(
            @WebParam(name = "code_id", partName = "code_id")
            String codeId);

    /**
     *
     * @param libTxt
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheCphTxt
     */
    @WebMethod(operationName = "get_the_cph_txt", action = "http://www.ws-theriaque.localhost/server.php#get_the_cph_txt")
    @WebResult(partName = "return")
    ArrayOfRowGetTheCphTxt getTheCphTxt(
            @WebParam(name = "lib_txt", partName = "lib_txt")
            String libTxt);

    /**
     *
     * @param codeId
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheCphSpe
     */
    @WebMethod(operationName = "get_the_cph_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_cph_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheCphSpe getTheCphSpe(
            @WebParam(name = "code_id", partName = "code_id")
            String codeId);

    /**
     * Enter description here ...
     *
     * @param code
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheGrFicSpe
     */
    @WebMethod(operationName = "get_the_gr_fic_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_gr_fic_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheGrFicSpe getTheGrFicSpe(
            @WebParam(name = "code", partName = "code")
            String code);

    /**
     * Enter description here ...
     *
     * @param code
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheAlFicSpe
     */
    @WebMethod(operationName = "get_the_al_fic_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_al_fic_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheAlFicSpe getTheAlFicSpe(
            @WebParam(name = "code", partName = "code")
            String code);

    /**
     * Enter description here ...
     *
     * @param code
     * @param fiche
     * @param vartype
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheGrSpe
     */
    @WebMethod(operationName = "get_the_gr_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_gr_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheGrSpe getTheGrSpe(
            @WebParam(name = "code", partName = "code")
            String code,
            @WebParam(name = "fiche", partName = "fiche")
            String fiche,
            @WebParam(name = "vartype", partName = "vartype")
            String vartype);

    /**
     * Enter description here ...
     *
     * @param code
     * @param fiche
     * @param vartype
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheAlSpe
     */
    @WebMethod(operationName = "get_the_al_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_al_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheAlSpe getTheAlSpe(
            @WebParam(name = "code", partName = "code")
            String code,
            @WebParam(name = "fiche", partName = "fiche")
            String fiche,
            @WebParam(name = "vartype", partName = "vartype")
            String vartype);

    /**
     * Enter description here ...
     *
     * @param code
     * @param fiche
     * @param vartype
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheFproSpe
     */
    @WebMethod(operationName = "get_the_fpro_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_fpro_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheFproSpe getTheFproSpe(
            @WebParam(name = "code", partName = "code")
            String code,
            @WebParam(name = "fiche", partName = "fiche")
            String fiche,
            @WebParam(name = "vartype", partName = "vartype")
            String vartype);

    /**
     * Enter description here ...
     *
     * @param code
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheCinetiqueSpe
     */
    @WebMethod(operationName = "get_the_cinetique_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_cinetique_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheCinetiqueSpe getTheCinetiqueSpe(
            @WebParam(name = "code", partName = "code")
            String code);

    /**
     * Enter description here ...
     *
     * @param code
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheSecuprecliniqueSpe
     */
    @WebMethod(operationName = "get_the_secupreclinique_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_secupreclinique_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheSecuprecliniqueSpe getTheSecuprecliniqueSpe(
            @WebParam(name = "code", partName = "code")
            String code);

    /**
     * Enter description here ...
     *
     * @param code
     * @param fiche
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheRefSecupreclinique
     */
    @WebMethod(operationName = "get_the_ref_secupreclinique", action = "http://www.ws-theriaque.localhost/server.php#get_the_ref_secupreclinique")
    @WebResult(partName = "return")
    ArrayOfRowGetTheRefSecupreclinique getTheRefSecupreclinique(
            @WebParam(name = "code", partName = "code")
            String code,
            @WebParam(name = "fiche", partName = "fiche")
            String fiche);

    /**
     * Enter description here ...
     *
     * @param code
     * @param vartype
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheDetPhdyna
     */
    @WebMethod(operationName = "get_the_det_phdyna", action = "http://www.ws-theriaque.localhost/server.php#get_the_det_phdyna")
    @WebResult(partName = "return")
    ArrayOfRowGetTheDetPhdyna getTheDetPhdyna(
            @WebParam(name = "code", partName = "code")
            String code,
            @WebParam(name = "vartype", partName = "vartype")
            String vartype);

    /**
     * Enter description here ...
     *
     * @param code
     * @param fiche
     * @param vartype
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheDetEtio
     */
    @WebMethod(operationName = "get_the_det_etio", action = "http://www.ws-theriaque.localhost/server.php#get_the_det_etio")
    @WebResult(partName = "return")
    ArrayOfRowGetTheDetEtio getTheDetEtio(
            @WebParam(name = "code", partName = "code")
            String code,
            @WebParam(name = "fiche", partName = "fiche")
            String fiche,
            @WebParam(name = "vartype", partName = "vartype")
            String vartype);

    /**
     * Enter description here ...
     *
     * @param code
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheEtioSpe
     */
    @WebMethod(operationName = "get_the_etio_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_etio_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheEtioSpe getTheEtioSpe(
            @WebParam(name = "code", partName = "code")
            String code);

    /**
     * Enter description here ...
     *
     * @param listeid
     * @param vty
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheIncompId
     */
    @WebMethod(operationName = "get_the_incomp_id", action = "http://www.ws-theriaque.localhost/server.php#get_the_incomp_id")
    @WebResult(partName = "return")
    ArrayOfRowGetTheIncompId getTheIncompId(
            @WebParam(name = "listeid", partName = "listeid")
            String listeid,
            @WebParam(name = "vty", partName = "vty")
            String vty);

    /**
     * Enter description here ...
     *
     * @param idspe
     * @param vty
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheIncompIdUn
     */
    @WebMethod(operationName = "get_the_incomp_id_un", action = "http://www.ws-theriaque.localhost/server.php#get_the_incomp_id_un")
    @WebResult(partName = "return")
    ArrayOfRowGetTheIncompIdUn getTheIncompIdUn(
            @WebParam(name = "idspe", partName = "idspe")
            String idspe,
            @WebParam(name = "vty", partName = "vty")
            String vty);

    /**
     * Enter description here ...
     *
     * @param listfic
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheIncompTxt
     */
    @WebMethod(operationName = "get_the_incomp_txt", action = "http://www.ws-theriaque.localhost/server.php#get_the_incomp_txt")
    @WebResult(partName = "return")
    ArrayOfRowGetTheIncompTxt getTheIncompTxt(
            @WebParam(name = "listfic", partName = "listfic")
            String listfic);

    /**
     * Enter description here ...
     *
     * @param idT1
     * @param idT2
     * @param nofic
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheIncompDet
     */
    @WebMethod(operationName = "get_the_incomp_det", action = "http://www.ws-theriaque.localhost/server.php#get_the_incomp_det")
    @WebResult(partName = "return")
    ArrayOfRowGetTheIncompDet getTheIncompDet(
            @WebParam(name = "nofic", partName = "nofic")
            String nofic,
            @WebParam(name = "id_t1", partName = "id_t1")
            String idT1,
            @WebParam(name = "id_t2", partName = "id_t2")
            String idT2);

    /**
     * Enter description here ...
     *
     * @param code1
     * @param code2
     * @param typeic
     * @param typeid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheInc
     */
    @WebMethod(operationName = "get_the_inc", action = "http://www.ws-theriaque.localhost/server.php#get_the_inc")
    @WebResult(partName = "return")
    ArrayOfRowGetTheInc getTheInc(
            @WebParam(name = "code1", partName = "code1")
            String code1,
            @WebParam(name = "code2", partName = "code2")
            String code2,
            @WebParam(name = "typeic", partName = "typeic")
            String typeic,
            @WebParam(name = "typeid", partName = "typeid")
            String typeid);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @param typeid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheDetInc
     */
    @WebMethod(operationName = "get_the_det_inc", action = "http://www.ws-theriaque.localhost/server.php#get_the_det_inc")
    @WebResult(partName = "return")
    ArrayOfRowGetTheDetInc getTheDetInc(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid,
            @WebParam(name = "typeid", partName = "typeid")
            String typeid);

    /**
     * Enter description here ...
     *
     * @param idspe
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheFcoIdBySpe
     */
    @WebMethod(operationName = "get_the_fco_id_by_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_fco_id_by_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheFcoIdBySpe getTheFcoIdBySpe(
            @WebParam(name = "idspe", partName = "idspe")
            String idspe);

    /**
     * Enter description here ...
     *
     * @param idfco
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheDetFco
     */
    @WebMethod(operationName = "get_the_det_fco", action = "http://www.ws-theriaque.localhost/server.php#get_the_det_fco")
    @WebResult(partName = "return")
    ArrayOfRowGetTheDetFco getTheDetFco(
            @WebParam(name = "idfco", partName = "idfco")
            String idfco);

    /**
     * Enter description here ...
     *
     * @param libtxt
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheLabTxt
     */
    @WebMethod(operationName = "get_the_lab_txt", action = "http://www.ws-theriaque.localhost/server.php#get_the_lab_txt")
    @WebResult(partName = "return")
    ArrayOfRowGetTheLabTxt getTheLabTxt(
            @WebParam(name = "libtxt", partName = "libtxt")
            String libtxt);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheLabId
     */
    @WebMethod(operationName = "get_the_lab_id", action = "http://www.ws-theriaque.localhost/server.php#get_the_lab_id")
    @WebResult(partName = "return")
    ArrayOfRowGetTheLabId getTheLabId(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @param typeid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheLabSpe
     */
    @WebMethod(operationName = "get_the_lab_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_lab_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheLabSpe getTheLabSpe(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid,
            @WebParam(name = "typeid", partName = "typeid")
            String typeid);

    /**
     * Enter description here ...
     *
     * @param lstsp
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheRedon
     */
    @WebMethod(operationName = "get_the_redon", action = "http://www.ws-theriaque.localhost/server.php#get_the_redon")
    @WebResult(partName = "return")
    ArrayOfRowGetTheRedon getTheRedon(
            @WebParam(name = "lstsp", partName = "lstsp")
            String lstsp);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheRecadmSpe
     */
    @WebMethod(operationName = "get_the_recadm_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_recadm_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheRecadmSpe getTheRecadmSpe(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid);

    /**
     *
     * @param codeid
     * @param ficid
     * @param typeid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheRecadmId
     */
    @WebMethod(operationName = "get_the_recadm_id", action = "http://www.ws-theriaque.localhost/server.php#get_the_recadm_id")
    @WebResult(partName = "return")
    ArrayOfRowGetTheRecadmId getTheRecadmId(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid,
            @WebParam(name = "ficid", partName = "ficid")
            String ficid,
            @WebParam(name = "typeid", partName = "typeid")
            String typeid);

    /**
     * Enter description here ...
     *
     * @param libtxt
     * @param monovir
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetThePdtTxt
     */
    @WebMethod(operationName = "get_the_pdt_txt", action = "http://www.ws-theriaque.localhost/server.php#get_the_pdt_txt")
    @WebResult(partName = "return")
    ArrayOfRowGetThePdtTxt getThePdtTxt(
            @WebParam(name = "libtxt", partName = "libtxt")
            String libtxt,
            @WebParam(name = "monovir", partName = "monovir")
            String monovir);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetThePdtId
     */
    @WebMethod(operationName = "get_the_pdt_id", action = "http://www.ws-theriaque.localhost/server.php#get_the_pdt_id")
    @WebResult(partName = "return")
    ArrayOfRowGetThePdtId getThePdtId(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid);

    /**
     * Enter description here ...
     *
     * @param libtxt
     * @param vartype
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheSubTxt
     */
    @WebMethod(operationName = "get_the_sub_txt", action = "http://www.ws-theriaque.localhost/server.php#get_the_sub_txt")
    @WebResult(partName = "return")
    ArrayOfRowGetTheSubTxt getTheSubTxt(
            @WebParam(name = "libtxt", partName = "libtxt")
            String libtxt,
            @WebParam(name = "vartype", partName = "vartype")
            String vartype);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @param vartype
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheSubId
     */
    @WebMethod(operationName = "get_the_sub_id", action = "http://www.ws-theriaque.localhost/server.php#get_the_sub_id")
    @WebResult(partName = "return")
    ArrayOfRowGetTheSubId getTheSubId(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid,
            @WebParam(name = "vartype", partName = "vartype")
            String vartype);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheExpId
     */
    @WebMethod(operationName = "get_the_exp_id", action = "http://www.ws-theriaque.localhost/server.php#get_the_exp_id")
    @WebResult(partName = "return")
    ArrayOfRowGetTheExpId getTheExpId(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @param typid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheSubSpe
     */
    @WebMethod(operationName = "get_the_sub_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_sub_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheSubSpe getTheSubSpe(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid,
            @WebParam(name = "typid", partName = "typid")
            String typid);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheSubPreccompSpe
     */
    @WebMethod(operationName = "get_the_sub_preccomp_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_sub_preccomp_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheSubPreccompSpe getTheSubPreccompSpe(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheSubTeneurSpe
     */
    @WebMethod(operationName = "get_the_sub_teneur_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_sub_teneur_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheSubTeneurSpe getTheSubTeneurSpe(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @param typid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheDetExp
     */
    @WebMethod(operationName = "get_the_det_exp", action = "http://www.ws-theriaque.localhost/server.php#get_the_det_exp")
    @WebResult(partName = "return")
    ArrayOfRowGetTheDetExp getTheDetExp(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid,
            @WebParam(name = "typid", partName = "typid")
            String typid);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @param typid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheDetSubact
     */
    @WebMethod(operationName = "get_the_det_subact", action = "http://www.ws-theriaque.localhost/server.php#get_the_det_subact")
    @WebResult(partName = "return")
    ArrayOfRowGetTheDetSubact getTheDetSubact(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid,
            @WebParam(name = "typid", partName = "typid")
            String typid);

    /**
     * Enter description here ...
     *
     * @param libcod
     * @param typ
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheAllergie
     */
    @WebMethod(operationName = "get_the_allergie", action = "http://www.ws-theriaque.localhost/server.php#get_the_allergie")
    @WebResult(partName = "return")
    ArrayOfRowGetTheAllergie getTheAllergie(
            @WebParam(name = "typ", partName = "typ")
            int typ,
            @WebParam(name = "libcod", partName = "libcod")
            String libcod);

    /**
     * Enter description here ...
     *
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheInfos
     */
    @WebMethod(operationName = "get_the_infos", action = "http://www.ws-theriaque.localhost/server.php#get_the_infos")
    @WebResult(partName = "return")
    ArrayOfRowGetTheInfos getTheInfos();

    /**
     * Enter description here ...
     *
     * @param codeid
     * @param typid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheDopage
     */
    @WebMethod(operationName = "get_the_dopage", action = "http://www.ws-theriaque.localhost/server.php#get_the_dopage")
    @WebResult(partName = "return")
    ArrayOfRowGetTheDopage getTheDopage(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid,
            @WebParam(name = "typid", partName = "typid")
            int typid);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @param typid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetThePrestation
     */
    @WebMethod(operationName = "get_the_prestation", action = "http://www.ws-theriaque.localhost/server.php#get_the_prestation")
    @WebResult(partName = "return")
    ArrayOfRowGetThePrestation getThePrestation(
            @WebParam(name = "codeid", partName = "codeid")
            int codeid,
            @WebParam(name = "typid", partName = "typid")
            int typid);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheSecabilite
     */
    @WebMethod(operationName = "get_the_secabilite", action = "http://www.ws-theriaque.localhost/server.php#get_the_secabilite")
    @WebResult(partName = "return")
    ArrayOfRowGetTheSecabilite getTheSecabilite(
            @WebParam(name = "codeid", partName = "codeid")
            int codeid);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @param typid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheConducteur
     */
    @WebMethod(operationName = "get_the_conducteur", action = "http://www.ws-theriaque.localhost/server.php#get_the_conducteur")
    @WebResult(partName = "return")
    ArrayOfRowGetTheConducteur getTheConducteur(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid,
            @WebParam(name = "typid", partName = "typid")
            int typid);

    /**
     * Enter description here ...
     *
     * @param typComposant
     * @param typid
     * @param var
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheComposant
     */
    @WebMethod(operationName = "get_the_composant", action = "http://www.ws-theriaque.localhost/server.php#get_the_composant")
    @WebResult(partName = "return")
    ArrayOfRowGetTheComposant getTheComposant(
            @WebParam(name = "typid", partName = "typid")
            int typid,
            @WebParam(name = "var", partName = "var")
            String var,
            @WebParam(name = "typ_composant", partName = "typ_composant")
            String typComposant);

    /**
     * Enter description here ...
     *
     * @param dc
     * @param type
     * @param var
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheDenominationCommune
     */
    @WebMethod(operationName = "get_the_denomination_commune", action = "http://www.ws-theriaque.localhost/server.php#get_the_denomination_commune")
    @WebResult(partName = "return")
    ArrayOfRowGetTheDenominationCommune getTheDenominationCommune(
            @WebParam(name = "type", partName = "type")
            int type,
            @WebParam(name = "var", partName = "var")
            String var,
            @WebParam(name = "dc", partName = "dc")
            int dc);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @param vartype
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheUcdCondPrim
     */
    @WebMethod(operationName = "get_the_ucd_cond_prim", action = "http://www.ws-theriaque.localhost/server.php#get_the_ucd_cond_prim")
    @WebResult(partName = "return")
    ArrayOfRowGetTheUcdCondPrim getTheUcdCondPrim(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid,
            @WebParam(name = "vartype", partName = "vartype")
            int vartype);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @param typeid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheDescPres
     */
    @WebMethod(operationName = "get_the_desc_pres", action = "http://www.ws-theriaque.localhost/server.php#get_the_desc_pres")
    @WebResult(partName = "return")
    ArrayOfRowGetTheDescPres getTheDescPres(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid,
            @WebParam(name = "typeid", partName = "typeid")
            String typeid);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @param typid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheSolvant
     */
    @WebMethod(operationName = "get_the_solvant", action = "http://www.ws-theriaque.localhost/server.php#get_the_solvant")
    @WebResult(partName = "return")
    ArrayOfRowGetTheSolvant getTheSolvant(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid,
            @WebParam(name = "typid", partName = "typid")
            int typid);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @param typid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheFormePrincipale
     */
    @WebMethod(operationName = "get_the_forme_principale", action = "http://www.ws-theriaque.localhost/server.php#get_the_forme_principale")
    @WebResult(partName = "return")
    ArrayOfRowGetTheFormePrincipale getTheFormePrincipale(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid,
            @WebParam(name = "typid", partName = "typid")
            int typid);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @param vartype
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheDoseTotUcd
     */
    @WebMethod(operationName = "get_the_dose_tot_ucd", action = "http://www.ws-theriaque.localhost/server.php#get_the_dose_tot_ucd")
    @WebResult(partName = "return")
    ArrayOfRowGetTheDoseTotUcd getTheDoseTotUcd(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid,
            @WebParam(name = "vartype", partName = "vartype")
            int vartype);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @param typid
     * @return
     *     returns com.orbis.sdb.control.theriaque.RowGetThePresdel
     */
    @WebMethod(operationName = "get_the_presdel", action = "http://www.ws-theriaque.localhost/server.php#get_the_presdel")
    @WebResult(partName = "return")
    RowGetThePresdel getThePresdel(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid,
            @WebParam(name = "typid", partName = "typid")
            String typid);

    /**
     * Enter description here ...
     *
     * @param codeid
     * @param typid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheIndicationSynth
     */
    @WebMethod(operationName = "get_the_indication_synth", action = "http://www.ws-theriaque.localhost/server.php#get_the_indication_synth")
    @WebResult(partName = "return")
    ArrayOfRowGetTheIndicationSynth getTheIndicationSynth(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid,
            @WebParam(name = "typid", partName = "typid")
            int typid);

    /**
     * Enter description here ...
     *
     * @param listcodes
     * @param typid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheUnite
     */
    @WebMethod(operationName = "get_the_unite", action = "http://www.ws-theriaque.localhost/server.php#get_the_unite")
    @WebResult(partName = "return")
    ArrayOfRowGetTheUnite getTheUnite(
            @WebParam(name = "listcodes", partName = "listcodes")
            String listcodes,
            @WebParam(name = "typid", partName = "typid")
            int typid);

    /**
     *
     * @param libtxt
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheIndTxt
     */
    @WebMethod(operationName = "get_the_ind_txt", action = "http://www.ws-theriaque.localhost/server.php#get_the_ind_txt")
    @WebResult(partName = "return")
    ArrayOfRowGetTheIndTxt getTheIndTxt(
            @WebParam(name = "libtxt", partName = "libtxt")
            String libtxt);

    /**
     *
     * @param codeid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheIndSpe
     */
    @WebMethod(operationName = "get_the_ind_spe", action = "http://www.ws-theriaque.localhost/server.php#get_the_ind_spe")
    @WebResult(partName = "return")
    ArrayOfRowGetTheIndSpe getTheIndSpe(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid);

    /**
     *
     * @param idfic
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheIndSpePrf
     */
    @WebMethod(operationName = "get_the_ind_spe_prf", action = "http://www.ws-theriaque.localhost/server.php#get_the_ind_spe_prf")
    @WebResult(partName = "return")
    ArrayOfRowGetTheIndSpePrf getTheIndSpePrf(
            @WebParam(name = "idfic", partName = "idfic")
            String idfic);

    /**
     *
     * @param codeid
     * @param typid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheDetInd
     */
    @WebMethod(operationName = "get_the_det_ind", action = "http://www.ws-theriaque.localhost/server.php#get_the_det_ind")
    @WebResult(partName = "return")
    ArrayOfRowGetTheDetInd getTheDetInd(
            @WebParam(name = "codeid", partName = "codeid")
            String codeid,
            @WebParam(name = "typid", partName = "typid")
            String typid);

    /**
     *
     * @param listCodes
     * @param typid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetThePrixUnitEst
     */
    @WebMethod(operationName = "get_the_prix_unit_est", action = "http://www.ws-theriaque.localhost/server.php#get_the_prix_unit_est")
    @WebResult(partName = "return")
    ArrayOfRowGetThePrixUnitEst getThePrixUnitEst(
            @WebParam(name = "list_codes", partName = "list_codes")
            String listCodes,
            @WebParam(name = "typid", partName = "typid")
            String typid);

    /**
     * Enter description here ...
     *
     * @param statut
     * @param type
     * @param var
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheMedVirPere
     */
    @WebMethod(operationName = "get_the_med_vir_pere", action = "http://www.ws-theriaque.localhost/server.php#get_the_med_vir_pere")
    @WebResult(partName = "return")
    ArrayOfRowGetTheMedVirPere getTheMedVirPere(
            @WebParam(name = "type", partName = "type")
            String type,
            @WebParam(name = "var", partName = "var")
            String var,
            @WebParam(name = "statut", partName = "statut")
            String statut);

    /**
     * Enter description here ...
     *
     * @param codeId
     * @param typeId
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetThePresentationV2
     */
    @WebMethod(operationName = "get_the_presentation_v2", action = "http://www.ws-theriaque.localhost/server.php#get_the_presentation_v2")
    @WebResult(partName = "return")
    ArrayOfRowGetThePresentationV2 getThePresentationV2(
            @WebParam(name = "code_id", partName = "code_id")
            String codeId,
            @WebParam(name = "type_id", partName = "type_id")
            String typeId);

    /**
     * Enter description here ...
     *
     * @param libtxt
     * @param typ
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheTerrain
     */
    @WebMethod(operationName = "get_the_terrain", action = "http://www.ws-theriaque.localhost/server.php#get_the_terrain")
    @WebResult(partName = "return")
    ArrayOfRowGetTheTerrain getTheTerrain(
            @WebParam(name = "libtxt", partName = "libtxt")
            String libtxt,
            @WebParam(name = "typ", partName = "typ")
            String typ);

    /**
     * Enter description here ...
     *
     * @param codid
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheUrl
     */
    @WebMethod(operationName = "get_the_url", action = "http://www.ws-theriaque.localhost/server.php#get_the_url")
    @WebResult(partName = "return")
    ArrayOfRowGetTheUrl getTheUrl(
            @WebParam(name = "codid", partName = "codid")
            String codid);

    /**
     * Enter description here ...
     *
     * @param codeId
     * @param monoVir
     * @param varType
     * @return
     *     returns com.orbis.sdb.control.theriaque.ArrayOfRowGetTheSpecialiteMultiCodeid
     */
    @WebMethod(operationName = "get_the_specialite_multi_codeid", action = "http://www.ws-theriaque.localhost/server.php#get_the_specialite_multi_codeid")
    @WebResult(partName = "return")
    ArrayOfRowGetTheSpecialiteMultiCodeid getTheSpecialiteMultiCodeid(
            @WebParam(name = "code_id", partName = "code_id")
            String codeId,
            @WebParam(name = "var_type", partName = "var_type")
            String varType,
            @WebParam(name = "mono_vir", partName = "mono_vir")
            String monoVir);

}
